version: 2.1
jobs:
  build:
    working_directory: .
    docker:
      - image: circleci/node:11.7.0
  steps:
    - checkout
    - run:
      name: Install Lerna
      command: yarn add -g lerna
    - run:
      name: Install packages
      command: yarn install --freeze-lockfile

    # Run tests
    - run: yarn ci:test
