version: 2.1
orbs:
  codecov: codecov/codecov@1.0.4
jobs:
  build:
    docker:
      - image: circleci/node:11.7.0
      - image: circleci/mongo:4.1.9-ram
    steps:
      - checkout
      - run:
          name: Install packages
          command: yarn install --freeze-lockfile
      - run:
          name: Lerna Boostrap
          command: yarn run bootstrap

      - run: yarn ci:test
      - store_test_results:
          path: packages/server/coverage
      - codecov/upload:
          flags: backend,unittest
