version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:11.7.0
      - image: circleci/mongo:4.1.9-ram
    steps:
      - checkout
      - run:
          name: Install packages
          command: yarn install --freeze-lockfile
      - run:
          name: Lerna Boostrap
          command: yarn run bootstrap

      - run: |
          yarn global add codecov

      - run: yarn ci:test
      - run: |
          cd packages/server
          codecov
      - store_artifacts:
          path: packages/server/coverage/clover.xml
      - store_test_results:
          path: packages/server/coverage/clover.xml
